Multi-line git aliases

diff --git a/gitconfig b/gitconfig
--- a/gitconfig
+++ b/gitconfig
@@ -11,29 +11,124 @@
 	revert = checkout --
 	amend = commit --amend
 	ama = commit --amend -a
-	curbr = "!f() { if [ ! -f .git/rebase-merge/head-name ]; then git rev-parse --abbrev-ref HEAD; else echo -n \"rb($(basename \"$(cat .git/rebase-merge/head-name)\")\"; if [ -f .git/rebase-merge/stopped-sha ]; then echo -n ',stopped'; fi; if (( $(git diff --name-only --diff-filter=U --relative | wc -l) != 0 )); then echo -n ',conflict'; fi; echo ')'; fi }; f"
+	curbr = "!f() { \
+	    if [ ! -f .git/rebase-merge/head-name ]; then \
+	        git rev-parse --abbrev-ref HEAD; \
+	    else \
+	        echo -n \"rb($(basename \"$(cat .git/rebase-merge/head-name)\")\"; \
+	        if [ -f .git/rebase-merge/stopped-sha ]; then \
+	            echo -n ',stopped'; \
+	        fi; \
+	        if (( $(git diff --name-only --diff-filter=U --relative | wc -l) != 0 )); then \
+	            echo -n ',conflict'; \
+	        fi; \
+	        echo ')'; \
+	    fi; \
+	}; f"
 	root = rev-parse --show-toplevel
 	set-upstream = remote set-head upstream
 	reset-upstream = remote set-head upstream --auto
-	head = "!f() { if [ -z \"$1\" ]; then echo 'error: no remote specified' >&2; return 1; fi; git symbolic-ref refs/remotes/$1/HEAD; }; f"
-	mbr = "!f() { if ! git head upstream >/dev/null 2>&1; then git reset-upstream; fi; set -o pipefail; git head upstream | cut -f4 -d/; }; f"
+	head = "!f() { \
+	    if [ -z \"$1\" ]; then \
+	        echo 'error: no remote specified' >&2; \
+	        return 1; \
+	    fi; \
+	    git symbolic-ref refs/remotes/$1/HEAD; \
+	}; f"
+	mbr = "!f() { \
+	    if ! git head upstream >/dev/null 2>&1; then \
+	        git reset-upstream; \
+	    fi; \
+	    set -o pipefail; \
+	    git head upstream | cut -f4 -d/; \
+	}; f"
 	fup = fetch upstream
 	rb = rebase
-	rbup = "!f() { echo \"Rebasing onto $(git mbr)\"; git rebase upstream/$(git mbr) \"$@\"; }; f"
+	rbup = "!f() { \
+	    echo \"Rebasing onto $(git mbr)\"; \
+	    git rebase upstream/$(git mbr) \"$@\"; \
+	}; f"
 	po = push origin
 	pocur = !git po $(git curbr)
 	pofcur = !git po -f $(git curbr)
 	wdiff = diff --color-words
-	safebr = "!f() { git co master || git co main }; f"
-	track = "!f() { if [ -z \"$1\" ]; then echo 'error: no remote or branch specified' >&2; return 1; fi; rmt=upstream. br=$1; if [ -n \"$2\" ]; then rmt=$1; br=$2; fi; git fetch $rmt $br && git co -b $br $rmt/$br; }; f"
-	retrack = "!f() { if [ -z \"$1\" ]; then echo 'error: no remote or branch specified' >&2; return 1; fi; rmt=upstream. br=$1; if [ -n \"$2\" ]; then rmt=$1; br=$2; fi; git safebr; if [ -n \"$(git br -l $br)\" ]; then git br -D $br || return 1; fi; git track $rmt $br; }; f"
-	copr = "!f() { if [ -z \"$1\" ]; then echo 'error: no remote or PR specified' >&2; return 1; fi; rmt=upstream; pr=$1; if [ -n \"$2\" ]; then rmt=$1; pr=$2; fi; git fetch $rmt pull/$pr/head:pr-$rmt-$pr; git co pr-$rmt-$pr;}; f"
-	recopr = "!f() { if [ -z \"$1\" ]; then echo 'error: no remote or PR specified' >&2; return 1; fi; rmt=upstream; pr=$1; if [ -n \"$2\" ]; then rmt=$1; pr=$2; fi; git safebr; git br -D pr-$rmt-$pr; git copr $rmt $pr;}; f"
+	safebr = "!f() { git co master || git co main; }; f"
+	track = "!f() { \
+	    if [ -z \"$1\" ]; then \
+	        echo 'error: no remote or branch specified' >&2; \
+	        return 1; \
+	    fi; \
+	    rmt=upstream; \
+	    br=$1; \
+	    if [ -n \"$2\" ]; then \
+	        rmt=$1; \
+	        br=$2; \
+	    fi; \
+	    git fetch $rmt $br && git co -b $br $rmt/$br; \
+	}; f"
+	retrack = "!f() { \
+	    if [ -z \"$1\" ]; then \
+	        echo 'error: no remote or branch specified' >&2; \
+	        return 1; \
+	    fi; \
+	    rmt=upstream; \
+	    br=$1; \
+	    if [ -n \"$2\" ]; then \
+	        rmt=$1; \
+	        br=$2; \
+	    fi; \
+	    git safebr; \
+	    if [ -n \"$(git br -l $br)\" ]; then \
+	        git br -D $br || return 1; \
+	    fi; \
+	    git track $rmt $br; \
+	}; f"
+	copr = "!f() { \
+	    if [ -z \"$1\" ]; then \
+	        echo 'error: no remote or PR specified' >&2; \
+	        return 1; \
+	    fi; \
+	    rmt=upstream; \
+	    pr=$1; \
+	    if [ -n \"$2\" ]; then \
+	        rmt=$1; \
+	        pr=$2; \
+	    fi; \
+	    git fetch $rmt pull/$pr/head:pr-$rmt-$pr; \
+	    git co pr-$rmt-$pr; \
+	}; f"
+	recopr = "!f() { \
+	    if [ -z \"$1\" ]; then \
+	        echo 'error: no remote or PR specified' >&2; \
+	        return 1; \
+	    fi; \
+	    rmt=upstream; \
+	    pr=$1; \
+	    if [ -n \"$2\" ]; then \
+	        rmt=$1; \
+	        pr=$2; \
+	    fi; \
+	    git safebr; \
+	    git br -D pr-$rmt-$pr; \
+	    git copr $rmt $pr; \
+	}; f"
 	wip = for-each-ref --sort='committerdate:iso8601' --format=' %(color:green)%(committerdate:relative)%09%(color:white)%(refname:short)' refs/heads
-	my = "!f() { git log --reverse --no-show-signature --format='format:%C(auto)%h  %s' upstream/$(git mbr)..HEAD; echo;}; f"
-	vs = "!f() { up=$1; test -z \"$1\" && up=upstream/$(git mbr); echo $up; git log --reverse --no-show-signature --format='format:%C(auto)%h  %s' ${up}..HEAD; echo;}; f"
+	my = "!f() { \
+	    git log --reverse --no-show-signature --format='format:%C(auto)%h  %s' upstream/$(git mbr)..HEAD; echo; \
+	}; f"
+	vs = "!f() { \
+	    up=$1; \
+	    test -z \"$1\" && up=upstream/$(git mbr); \
+	    echo $up; \
+	    git log --reverse --no-show-signature --format='format:%C(auto)%h  %s' ${up}..HEAD; echo; \
+	}; f"
 	unstage = restore --staged
-	kys = "!f() { curbr=$(git curbr); echo \"Nuking $curbr\"; sleep 3; git safebr && git br -D $curbr; }; f"
+	kys = "!f() { \
+	    curbr=$(git curbr); \
+	    echo \"Nuking $curbr\"; \
+	    sleep 3; \
+	    git safebr && git br -D $curbr; \
+	}; f"
 [core]
 	editor = "vim +0"
 	excludesFile = ~/.gitignore
